### PR TITLE
Add execution monitor to device app

### PR DESCRIPTION
**Pull request by dehanj**
Prevent instructions to be executed from the RAM outside the application.
This does change the sha512sum, and hence the key derivation.

### CODE REVIEW

**Comment by quite** [comment]
The `TK1_MMIO_TK1_APP_{ADDR,SIZE}` defines addresses where the app is loaded and its size respectively. You'd have to read out the values at these addresses, and then add those values together. Looks like the same for https://github.com/tillitis/tkey-device-signer/pull/3

**Comment by quite** [comment]
But thank you, i plan to bring this in after current rework of app is done. We're defining exactly how key derivation should work etc.

**Comment by dehanj** [comment]
Ah, good catch! It apparently went a bit fast on Thursday. I did it that way first and checked everything, then I for some reason wanted to use them the same way as TK1_RAM_{BASE,SIZE}...

Sure. Since I did it on all our repos (which I'm updating now) I thought I might as well do a PR for you. Thanks anyway.

**Comment by quite** [comment]
Fixed.

**Pull request closed without merging**
